### ISSUE TITLE
PLTT Parsing

### ISSUE THREAD

**Issue by scottrick** [MikeG621/LfdReader#4]
Working on parsing the PLTT resources.  It all works as you have described, except for the palettes found in CITY.LFD.  

In CITY.LFD, the two palettes have additional bytes at the end instead of the single reserved byte.  In all other cases, the reserved byte is zero.  In CITY.LFD, the reserved byte is "2", and then followed by 8 more bytes of info.  In both cases, it's the same:

`reserved: [2, 50, 1, 208, 209, 50, 7, 210, 214]`

I don't have any idea what those bytes are for, but was curious to see if you knew.

**Comment by MikeG621** [comment]
So I only stumbled upon that this was possible recently, but missed that
CITY actually used it so didn't dig deeper until now.  The first value of 2
is a count, and the next two values are actually 16-bit so we have [306,
208, 209] and [1842, 210, 214].
So far I've found that the last two in the set (so in this case 208/209 and
210/214) are start/end color index pairs, for limiting the loaded colors to
those specific ones.  The first number is some sort of display check to see
if this is even used in the scene.

So it's modifying how the PLTT is used in the view, but I'm not sure why.

**Comment by scottrick** [comment]
Interesting; thanks for the info.

**Comment by MikeG621** [comment]
Added ability to load the modifiers in 7ca8b9b as read-only

**Comment by scottrick** [comment]
I had another question about palettes and their usage in game.  Maybe you know the answer.

I'm working on making a custom Tour of Duty "Battle Bitmap" for a custom Tie Fighter Collector's CD-ROM battle.  Tie Fighter Workshop lets you specify a BMP for this purpose.  

What I understand, from reading your documentation and elsewhere, is that multiple palettes are loaded in game at a time, and combined together to make the "active palette".  For the Tour of Duty desk, there is palette "toddesk" inside TOURDESK.LFD.  It specifies 224 colors, starting at index 32.

What I *expected*, was that I would be able to take the general 32 color palette found in EMPIRE.LFD (the 16 basic colors and 16 grays, from index 0 to 31) and combine it with the 224 palette from TOURDESK.LDF and create a combined palette with a full 256 colors available.  However, in my testing, only the colors in the tourdesk color palette will ever correctly be displayed.  If I limit the battle bitmap image so it only uses the 224 colors in the toddesk palette, it works great.  

So it seems to me, that when being drawn, an image only has access to the colors in the latest palette (the toddesk palette), no matter what other colors may be already loaded (for example, the general EMPIRE.LFD palette).

In the end, I got my custom bitmap working and it looks great, But I had to limit the available colors to the 224 in the tourdesk palette.  It just wasn't what I had expected.

Does that line up with what you've seen?  Am I missing something?

**Comment by MikeG621** [comment]
YOGEME has this functionality, and it does what you think it should: it
loads EMPIRE:PLTTstandard first, then TOURDESK:PLTTtoddesk, combining to
make the full palette.
TIE at any time is managing multiple PLTTs and calls on portions of them at
a time to build up the full 256 palette.  This is more prevalent with
screens that are pieced together with variable elements (certain
cutscenes/views, medal awards, etc) where a view can be stacking up to 5
different PLTTs.

If you're using TFW to add your BMP, I would say try loading your 256 color
version with YOGEME to see if it behaves the same in-game.  I think one of
two things is going on: 1) TFW is encoding your image incorrectly by not
using PLTTstandard, or 2) TIE really is only using PLTTtoddesk to render
the system image for some reason.  I can do more digging on that, to see if
TIE itself is doing something weird.

Another thing to check if you haven't, is after you import your 256-color
version with TFW, if you completely close it and re-open can you get your
original 256-color back out, or does it only export the trimmed 224?.

**Comment by scottrick** [comment]
Oh, I didn't think of that!  I bet you're right and tfw isn't writing the DELT resource correctly.  I will test this and let you know, thanks!

**Comment by MikeG621** [comment]
Got it.  So those extra values in TOURDESK's PLTTs rotate a portion of the
PLTT, which produces a blinking or "twinkle" effect.  The 306 and 1842 are
effectively rate values, so the first set of [306, 208, 209] just toggles
the 208 and 209 colors at a slow speed (every 16 frames), and the second
set of [1842, 210, 214] rotate the colors from 210-214 at a faster rate
(every 2 frames).  If you look up the cutscenes on Youtube, you'll notice
the red lights at the tips of various buildings blink, and a couple
buildings have yellow lights that flash.  This is how that is done, by
manipulating the PLTT instead of loading new DELT/ANIM resources with
slightly different indexes.

**Comment by scottrick** [comment]
Wow, nice work tracking that down!  That makes sense to me.  How do you determine the rotation rate?  By the first value?

Also, I'm assuming you mean city.lfd, not the tour desk?

**Comment by MikeG621** [comment]
Yes, sorry. CITY.  Was scrolling up and down the thread for the values and
eye caught it from the other response.

Okay, the first value controls the rotation rate, and I'm sure the reason
why they're like this is due to something that existed before TIE, but it's
really a Frame Divider with a multiplier on it, such that (0x1333 /
Divider) = "n", and every "n" frames the colors are rotated.  So for the
first set for the red aerial indicators, 0x1333 / 306 = 16 frames, and the
yellow window lights, 0x1333 / 1842 = 2 frames.

So yes, the rotation rate is the first valueMessage ID:
***@***.***>

>

**Comment by scottrick** [comment]
I see.  Where does 0x1333 come from?  Or is that a standard value used back in the day?

**Comment by MikeG621** [comment]
No clue why it is that way, but that's how it works out for TIE.  You'd
think it'd be easier to store the 16 and 2 if it's counting frames.  My
guess is that sometime in the past when the format was created, a game
wasn't counting frames but was instead using the value as a frequency.Message
ID: ***@***.***>

>

**Comment by scottrick** [comment]
Very interesting.  Also, I am very curious how you figured this out?  Are you using a tool to help watch what the game is doing?  Or just experimenting?

I am fairly new to this sort of thing, and trying to pick up as many tips and tricks that I can!  :D

**Comment by MikeG621** [comment]
Most of my reverse engineering is done with a simple hex editor, and years
of knowledge to make educated guesses about how a file format *might* work,
and then I'll write my own tools to modify values one at a time to see if
the behavior changes the way I think it should or if the patterns I think
I'm seeing in one place are consistent in all cases.  Working out the
graphics formats sometimes required triggering a cutscene or re-flying a
test mission several times and mashing PrintScreen in order to get multiple
pixel-perfect frames instead of the blurry mess you see on Youtube.  As
more things get decoded, that provides clues to other pieces until you get
something that can almost fully automate cutscenes (I need to add the PLTT
Rotator ability now), edit a cockpit layout, or even something as simple as
making a patch so all TIEs have shields by default.  I have spreadsheets
where I'll line up the hex dump of multiple resources of the same type, to
look for patterns and block things out.  That helped decoding FILM
resources, pilot files, mission files, etc.

Sometimes I can use an editor that already exists to get a jump start on
the format, and then I keep digging to fill the gaps.  Sometimes it'll even
come from a different platform; there's things from XWA that explained
Unknowns in TIE and vice versa.

Very recently I started looking at the assembly itself, and like I
mentioned in my first reply I did actually see that these values could
exist, I just had no idea what they were doing or if they were ever
actually used so I didn't have any context, but you finding them in CITY
narrowed the search and from there it's back to old-fashion detective work
to see what's different.
LMessage ID: ***@***.***>

>

**Comment by scottrick** [comment]
Thanks for the insight, I appreciate it.

I guess I'm working in a similar manner, but still catching up on all the details that you and others have already figured out.  I hadn't thought of lining up the hex for similar sections of data and looking for patterns, that's a good idea.  I hope I can help contribute more in the future once my tool is more fleshed out.  Thank you!
