### ISSUE TITLE
PANL Resource

### ISSUE THREAD

**Issue by scottrick** [MikeG621/LfdReader#6]
I'm curious if you have noticed this while working with PANL files.  I didn't see anything in Panl.cs, but I may have missed it.

For an LFD file, like TIEFTR12.LFD, or TIEFTRFL.LFD, which is made up of a single PANL resource, I've noticed the LfdHeader "size" does not match the actual size of the file.  Do you know why there is extra data at the end?

**Comment by MikeG621** [comment]
Because they're not actually just a single PANL.  Cockpit LFDs don't use
RMAPs for some reason, but there are also MASK and PLTT resource in those
files.  Over in LfdFile.cs, there is a special type that accounts for it
when the first resource in a PANL, so it'll detect and load the other
resources even without the RMAP.Message ID: <MikeG621/LfdReader/issues/6@
github.com>

>

**Comment by scottrick** [comment]
Thank you!
